!function(a,b){"function"==typeof define&&define.amd?define([],b):"undefined"!=typeof module&&module.exports?module.exports=b():a.lscache=b()}(this,function(){function a(){var a="__lscachetest__",c=a;if(void 0!==n)return n;try{h(a,c),i(a),n=!0}catch(a){n=b(a)?!0:!1}return n}function b(a){return a&&"QUOTA_EXCEEDED_ERR"===a.name||"NS_ERROR_DOM_QUOTA_REACHED"===a.name||"QuotaExceededError"===a.name?!0:!1}function c(){return void 0===o&&(o=null!=window.JSON),o}function d(a){return a.replace(/[-[\]{}()*+?.,\\^$|#\s]/g,"\\$&");

}function e(a){return a+q}function f(){return Math.floor((new Date).getTime()/s)}function g(a){return localStorage.getItem(p+u+a)}function h(a,b){localStorage.removeItem(p+u+a),localStorage.setItem(p+u+a,b)}function i(a){localStorage.removeItem(p+u+a)}function j(a){for(var b=new RegExp("^"+p+d(u)+"(.*)"),c=localStorage.length-1;c>=0;--c){var f=localStorage.key(c);f=f&&f.match(b),f=f&&f[1],f&&f.indexOf(q)<0&&a(f,e(f))}}function k(a){var b=e(a);i(a),i(b)}function l(a){var b=e(a),c=g(b);if(c){var d=parseInt(c,r);

if(f()>=d)return i(a),i(b),!0}}function m(a,b){v&&"console"in window&&"function"==typeof window.console.warn&&(window.console.warn("lscache - "+a),b&&window.console.warn("lscache - The error was: "+b.message))}var n,o,p="lscache-",q="-cacheexpiration",r=10,s=6e4,t=Math.floor(864e13/s),u="",v=!1,w={set:function(d,l,n){if(a()){if("string"!=typeof l){if(!c())return;try{l=JSON.stringify(l)}catch(a){return}}try{h(d,l)}catch(a){if(!b(a))return void m("Could not add item with key '"+d+"'",a);var o,p=[];
j(function(a,b){var c=g(b);c=c?parseInt(c,r):t,p.push({key:a,size:(g(a)||"").length,expiration:c})}),p.sort(function(a,b){return b.expiration-a.expiration});for(var q=(l||"").length;p.length&&q>0;)o=p.pop(),m("Cache is full, removing item with key '"+d+"'"),k(o.key),q-=o.size;try{h(d,l)}catch(a){return void m("Could not add item with key '"+d+"', perhaps it's too big?",a)}}n?h(e(d),(f()+n).toString(r)):i(e(d))}},get:function(b){if(!a())return null;if(l(b))return null;var d=g(b);if(!d||!c())return d;

try{return JSON.parse(d)}catch(a){return d}},remove:function(b){a()&&k(b)},supported:function(){return a()},flush:function(){a()&&j(function(a){k(a)})},flushExpired:function(){a()&&j(function(a){l(a)})},setBucket:function(a){u=a},resetBucket:function(){u=""},enableWarnings:function(a){v=a}};return w});var $arrivals=document.getElementById("arrivals"),arrivalsTimeout,xhr=new XMLHttpRequest,showArrivals=function(a){return document.hidden||"hidden"==document.visibilityState?void(arrivalsTimeout=setTimeout(function(){
showArrivals(a)},2500)):(xhr.open("get","https://arrivelah.herokuapp.com/?id="+a,!0),xhr.onload=function(){$arrivals.classList.remove("fading");var b=JSON.parse(this.responseText);b&&!b.error&&($arrivals.innerHTML=b.services.sort(function(a,b){return null==a.next.duration_ms?1:null==b.next.duration_ms?-1:a.next.duration_ms-b.next.duration_ms}).map(function(a){return"<tr><th>"+a.no+"</th><td>"+timeDisplay(a.next.duration_ms)+"</td><td>"+timeDisplay(a.subsequent.duration_ms)+"</td></tr>"}).join(""),
arrivalsTimeout=setTimeout(function(){showArrivals(a)},15e3))},xhr.onerror=function(){arrivalsTimeout=setTimeout(function(){showArrivals(a)},5e3)},xhr.send(),void $arrivals.classList.add("fading"))},timeDisplay=function(a){if(null==a)return'<span class="insignificant">Unavailable</span>';var b=Math.ceil(a/1e3/60);return 0>=b?"Now":1==b?b+" min":b+" mins"},rootEndPoints={github:"../data/2/",s3:"https://busrouter-sg.s3-ap-southeast-1.amazonaws.com/v2/"},dataEndPoints={busStops:"bus-stops.json",busServices:"bus-services.json",
busService:"bus-services/{{no}}.json",busStopsServices:"bus-stops-services.json"},getData=function(a,b,c){2==arguments.length&&(c=b,b={});var d=lscache.get(a);if(d)c(null,d);else{var e=new XMLHttpRequest,f="withCredentials"in e&&"undefined"!=typeof GZIP_ENABLED&&GZIP_ENABLED,g=rootEndPoints[f?"s3":"github"]+dataEndPoints[a.split("-")[0]];for(p in b)g=g.replace("{{"+p+"}}",b[p]);f&&(g+="?"+ +new Date),e.onload=function(){try{var b=JSON.parse(this.responseText);c(null,b),lscache.set(a,b,1440)}catch(a){
c(a)}},e.onerror=e.onabort=c,e.open("get",g,!0),e.send()}};getData("busStops",function(a,b){var c=b.reduce(function(a,b){return a[b.no]=b,a},{});window.onhashchange=function(){var a=location.hash.slice(1),b=c[a];if(clearTimeout(arrivalsTimeout),a&&b){var d=b.lat+","+b.lng,e=a+" - "+b.name;document.title="Bus arrival times for "+e,document.getElementById("bus-stop-name").innerHTML=e,document.getElementById("bus-stop-heading").style.backgroundImage="url(https://maps.googleapis.com/maps/api/staticmap?"+["key=AIzaSyDJii3LssFIl3cw4XzTxtWqSls57rayV5I","center="+d,"zoom=16","scale=2","size=480x240","maptype=roadmap","format=png"].join("&")+")",
showArrivals(a)}else alert("Invalid bus stop code.")},window.onhashchange()});
//# sourceMappingURL=arrivals.js.map