const fs = require('fs');
const got = require('got');

(async() => {

let body = '';
try {
  const res = await got.post('http://overpass-api.de/api/interpreter', {
    body: `data=${encodeURIComponent(`
      /*
      This has been generated by the overpass-turbo wizard.
      The original search was:
      “"bus stop" in Singapore”
      */
      [out:json][timeout:25];
      // fetch area “Singapore” to search in
      area(3601769123)->.searchArea;
      // gather results
      (
        // query part for: “"bus stop"”
        node["highway"="bus_stop"](area.searchArea);
      );
      // print results
      out body;
      >;
      out skel qt;
    `)}`
  });
  body = res.body;
} catch (e) {
  console.error(e);
}


const filePath = 'data/3/stops.osm.json';
fs.writeFileSync(filePath, body);
console.log(`Generated ${filePath}`);

})();
